using Runiq.Cli.Models;

namespace Runiq.Cli.Planning;

public sealed class ProjectPlanner
{
    public ProjectPlan CreatePlan(ProjectDefinition definition)
    {
        var root = definition.Name;
        var apiProjectRoot = Path.Combine(root, "src", $"{definition.Name}.Api");
        var directories = new List<DirectoryPlan>
        {
            new() { Path = root },
            new() { Path = Path.Combine(root, "src") },
            new() { Path = apiProjectRoot },
            new() { Path = Path.Combine(apiProjectRoot, "Agents") },
            new() { Path = Path.Combine(apiProjectRoot, "Tools") },
            new() { Path = Path.Combine(apiProjectRoot, "Prompts") },
            new() { Path = Path.Combine(apiProjectRoot, "Workflows") },
            new() { Path = Path.Combine(root, "tests") }
        };

        if (definition.EnableMcp)
        {
            directories.Add(new DirectoryPlan { Path = Path.Combine(apiProjectRoot, "Mcp") });
        }

        return new ProjectPlan
        {
            Directories = directories,
            Files =
            [
                new FilePlan
                {
                    Path = Path.Combine(root, "README.md"),
                    Content = $"""
                    # {definition.Name}

                    Generated by Runiq CLI.

                    ## Try These Prompts

                    Open the Runiq Dashboard and try:

                    ```text
                    Can you suggest a 2-day trip plan in Istanbul for 3 people?
                    ```

                    More examples:

                    ```text
                    What is the weather like in Istanbul for this sample trip?
                    ```

                    ```text
                    Estimate the trip cost for 3 people over 2 days.
                    ```

                    ```text
                    Create a short Istanbul itinerary and include a simple budget estimate.
                    ```
                    """
                }
            ]
        };
    }
}
